services:
  
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME} 
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"    
    volumes:
      - db-data:/var/lib/postgressql 
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
