services:
  api:
  
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend


  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME} 
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"    
    volumes:
      - db-data:/var/lib/postgressql 
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
